apiVersion: v1
kind: Namespace
metadata:
  name: bp2s
---
apiVersion: v1
kind: Pod
metadata:
  name: storage
  namespace: bp2s
  labels:
    name: storage
spec:
  containers:
  - name: bp2s-storage-container
    image: cchantep/minio-test:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: storage-svc
  namespace: bp2s
spec:
  selector:
    name: storage
  ports:
    - protocol: TCP
      port: 9000
      name: s3
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  namespace: bp2s
  name: sftp
  labels:
    name: sftp
spec:
  containers:
  - name: bp2s-sftp-container
    image: cchantep/sftp-test:0.2
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-svc
  namespace: bp2s
spec:
  selector:
    name: sftp
  ports:
    - protocol: TCP
      port: 22
      name: sftp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zk-svc
  namespace: bp2s
spec:
  type: NodePort
  ports:
  - name: zk-port
    port: 2181
    # nodePort: 30181
    targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zk
  namespace: bp2s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: library/zookeeper
        imagePullPolicy: IfNotPresent
        name: zk-container
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"
---
  apiVersion: v1
  kind: Service
  metadata:
    name: kafka-svc
    namespace: bp2s
    labels:
      app: kafka
  spec:
    type: LoadBalancer
    ports:
    - port: 9092
      name: plaintext
    selector:
      app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bp2s-kafka
  namespace: bp2s
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka-svc"
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.12-2.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          name: plaintext
        env:
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: BROKER_ID_COMMAND
            value: "hostname | cut -d'-' -f3"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zk-svc:2181"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_CREATE_TOPICS
            value: "bp2s-sync:1:1"
---
apiVersion: v1
kind: Pod
metadata:
  name: bp2s-poll
  namespace: bp2s
spec:
  containers:
  - name: bp2s-poll-container
    image: avandel/sftp-poll:0.21
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: "1024Mi"
      requests:
        cpu: "1"
        memory: "1024Mi"
    env:
    - name: JVM_0PTS
      value: "-Xms1024M -Xmx1024M"
    - name: SYNC_INTERVAL
      value: "10"
    - name: SFTP_USER
      value: "test"
    - name: SFTP_PASSWORD
      value: "password"
    - name: SFTP_PATH
      value: "/csv_category_export/2730/output/"
    - name: S3_ACCESS_KEY_ID
      value: "minio"
    - name: S3_SECRET_KEY
      value: "minio123"
    - name: S3_BUCKET
      value: "poc-bp2s"
    - name: KAFKA_TOPIC
      value: "bp2s-sync"
    - name: SFTP_PK
      value: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdkswM3JyRmFCcVBMSzQyTFVsWUNoQzdmeXBmeUhMSExaQ2R0OVRMYml4ckhIMWJ2CkxOSmh6SGZRTlNVOXBCaVVLMnZuSkZxR1hJSTNRSlFmRkp2T2ZWMm8xc24wazR5KzhZOFhpRzcvbUgxYkIvSkEKVTEwYUw2cEZEcUpUYkQ2ZE8zVkxaSUFRL0V4eWI2bis2enlMUVJ4RUtQZkk5RVU3amZHQ0NqNFEvWFMwNldoVApCMDQxRzlLZDhOcG5sUjRjUEs0alFjK3pLc3lrNzMrM2ZHb0JqaFE0UXZabWsrcXY0OUcwZU1UVENEdlFvcTlUCnkwdmNGVGM2VUtyMzZGQUFsZHMzNEhVUHpqSGswRnlEeVIyMHd4TGs1bDhsNEovcVNUaGpYL1FnRU1XZm90WnYKZXBtQzcrNTZVS1FnZGZxTHlnRTFRczUxenhPLzJXWGZKR2U2WlFJREFRQUJBb0lCQUhicUVWTW44aDZITXpEUworQUUvdGp4TE1yOEVQeEw0dDhENjNPR1NXUzUyQlJQcWZiblpLc3hzb3l3cnVZcm45dExiSWdZV2krSllLNnltCjdtUFZ3ekhlU3VCOHpvb0VSZ0FHK0lVRHVGSUtoOG9kVTQ5MitWOGJTSVR0cC9oc0Nqc0VOUzAxVGY5RnkwWTMKZFRRYnA0UzA1UHlSRnZWbGdTQjRHMGFMVWJmN3RGa0hUQ2JoNnlDTXlhZTFjVWp4a01keGpxSFIwa3hrcjBWZwp4QTQ1b2phS1VxK01KQ2xQZWtDK3lLZTc0OXA5L1lRODE4RWIzNUErMlZBUzNDMEVWSmMvYU9GMVFqOGdyRnhGCnF2MkQzMEtuWWRCSVVtR3FoYXpBOXorbG9MdmVidDlXTlhFL3JmYTJWTWF0TVpkYkhkYWtHd283a1Rpd1BvUDYKS2JmRnRnRUNnWUVBOTdjbkRhakRVR0VEN3dHaHBmRlFTYlZtdDhhZWtudG8rOFdvbzhSR1EyWHJyMmVLTndEUwpQWHZWcmMvK09xU0RieHlISXErNU9YK0k3US9sYi90MndBVUw3SXBhTzYrSCtpSUFmZDU2K0RUYkJsSkdvS2g4CmIwUE4vLzhPRXl1cWVzT2hoTnlTSEo0NFpuQmwrd1JzVEJ1aExzbnNIbmpsN0E4VUJ3Tlk5WUVDZ1lFQXd2eVkKdlVibldpWjRSYnJmMzdQMmEyOHBTU01MUlZNOWxXZUxrUXVGUUFGK1A2eWhXOGx3cE8zalBSRUlIdlc5eGVJeApLcEcvblZKd084dFhRN0F1ZEt4VDlST0R5a1RpMC93dlhjbXJvMUl3Ujh0Y1ZyazI2aXUxTWhJOHFZZGVtS1JZCmdXNkE0YUppMmNEQ0ZWTnVFeVV4ZzBadnYwMlhtUDhqcXBhUEh1VUNnWUVBclRaU2hvaVZXaVVjWFFtbEFLWUcKWUNRS0dVTTNLbkpFN0pnLzNaT25GZ1cwa2NneXExZFZxMHhtRTgyMmxVYm42TS9uNW1jOWUya2tVNitqM1hQVwppMXA4QmdDUUsrQUhrdTRucmR2ZDNLVUk2aGlwN2praUdhTXQ3bTFvYUJ0R2IrVlBrZG15Q1hUUk4wQXM3eU1lCm52RksrYTZUL3BMSEl4TkFDODlaYXdFQ2dZQkdFRGZlQTJWTVNuaDdMZHdWNlBlSndTYkhwZlQ5MHh4VTNDRVYKWEZ0a0ZXVkZBZ1gxRWx3TWw0Skl4aDd4NlFGbzRvOGlLYjc5aThyU1lZMll2K3poZGE2eGFISzVzcWtDM1NJMApCQ3hOZ2xIZzZseml1S2pYMmg3QXdEYlYvOU5vNjl6MW5UeG9WMDVIeW5DeTh3aWhqb0xORmZrL2QyVWF6OHNFCkdCZVRWUUtCZ0hVaDJQK3JSaEZYWXVDQSt1bkE2V0xGdThvK01VQ1JxcXQ4SFZxSHIyNzhFeS93L3RmWW5hM1cKTTA4QnlxaWNoWmo4Tm84WmVNR1lhQ29KMTl5cGc5SjlnQVc3ZWZJeVhRYThMalV6WWxad0VPQ2RBUDQrV2RIbwpJYzBCOWVrUDRRZHJhRWcxQU9kdDRkY2lQaWJzWTZXU0JVQVdpK1QyR2lpYTF2VVh1ZG4vCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
